name: "ghactions"
repository: "42ByteLabs/ghactions"
version: 0.9.8
default: false

locations:
  - name: "Release file"
    paths:
      - ".release.yml"
    patterns:
      - '\nversion:\s*([0-9]+\.[0-9]+\.[0-9])'
  - name: "Cargo"
    exclude:
      - "/target/"
      - "/action-template/"
      - "/examples/"
    paths:
      - "Cargo.toml"
    patterns:
      - '\nversion\s*=\s*"([0-9]+\.[0-9]+\.[0-9])"'

