name: "ghactions"
repository: "42ByteLabs/ghactions"
version: 0.15.4

ecosystems:
  - Docs
  - Rust

locations:
  - name: "Cargo - Workmembers"
    paths:
      - "Cargo.toml"
      - "**/Cargo.toml"
    patterns:
      - 'ghactions = \{.*version\s*=\s*"\^{version}".*\}'
      - 'ghactions-core = \{.*version\s*=\s*"\^{version}".*\}'
      - 'ghactions-derive = \{.*version\s*=\s*"\^{version}".*\}'


