name: "ghactions"
repository: "42ByteLabs/ghactions"
version: 0.9.6
default: false

locations:
  - name: "Cargo"
    exclude:
      - "/target/"
      - "/action-template/"
      - "/examples/"
    paths:
      - "Cargo.toml"
    patterns:
      - '\nversion\s*=\s*"([0-9]+\.[0-9]+\.[0-9])"'

