[package]
name = "ghactions"
version = "0.7.0"
description = "GitHub Actions Crate"
keywords = ["github", "actions"]

homepage = "https://github.com/GeekMasher/ghactions"
repository = "https://github.com/GeekMasher/ghactions"
documentation = "https://docs.rs/ghactions/latest/ghactions/index.html"
authors = ["GeekMasher"]
license = "MIT"

edition = "2021"
rust-version = "1.70"

readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
thiserror = "1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
log = "0.4"
env_logger = "0.11"
octocrab = "0.38"

time = "0.3.36"

[dev-dependencies]
anyhow = "1"
log = "0.4"
tokio = { version = "1.37", default-features = false, features = [
    "macros",
    "rt-multi-thread",
    "time",
] }
