[package]
name = "ghactions"
version = "0.4.1"
description = "GitHub Actions Crate"
keywords = ["github", "actions"]

homepage = "https://github.com/GeekMasher/ghactions"
repository = "https://github.com/GeekMasher/ghactions"
documentation = "https://docs.rs/ghactions/latest/ghactions/index.html"
authors = ["GeekMasher"]
license = "MIT"

edition = "2021"
rust-version = "1.56"

readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
thiserror = "1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.2"
log = "0.4.17"
env_logger = "0.9.0"
octocrab = "0.17"

[dev-dependencies]
anyhow = "1"

