[template]
cargo_generate_version = ">=0.10.0"
sub_templates = ["action-template"]

[placeholders]
action_name = { prompt = "Enter Action name", default = "my_action", type = "string" }
project_owner = { prompt = "Enter Owner (organization or individual)", default = "my_org", type = "string" }
description = { type="string", prompt="Description of your Action?" }

