[package]
name = "{{crate_name}}"
version = "0.16.5"

edition = "2021"

[dependencies]
ghactions = {version = "^0.9", features = ["generate", "octocrab"]}
anyhow = "1"
log = "0.4"
tokio = { version = "^1.38", features = [ "full" ] }

