name: Cargo - Examples

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read 

jobs:
  examples:
    name: Examples
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        example: [ "basic", "advanced", "entrypoint" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Example - ${{ matrix.example }}
        uses: ./examples/${{ matrix.example }}/

