name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - '**'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v2
        
      - name: Build
        run: cargo build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v2
        with:
          components: clippy
      - run: cargo clippy --all-targets -- -D clippy::all

  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ matrix.rust }}
      - name: Run tests
        run: cargo test

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v2
      
      - name: Package
        run: cargo package
      
      - name: Publish
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
        run: cargo publish --token $CRATES_TOKEN
